name: extension

on:
  push:
    branches: [ "main" ]
    paths: [ "**.md[csx]?" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "**.md[csx]?" ]

jobs:
  cljfmt:

    runs-on: ubuntu-latest

    steps:
      - name: Notify
        run: echo "trigerred!"
